[7834029] Automated Fix
azsk/ADOScanner pull request #419
Opened 2021-09-08 10:55 UTC by iamPallav

## Description
</br>
 -Control changed and undofix added for ADO_Project_AuthZ_Restrict_Broader_Group_Access_on_Repo

## Checklist
- [ ] I have read the instructions mentioned in [Contribute to Code](/Contributing.md).
- [ ] I have read and understood the criteria described under [submitting changes](/Contributing.md#submitting-changes). 
- [ ] The title of the PR clearly describes the intent of the PR.
- [ ] This PR does not introduce any breaking changes to the code.

2021-09-08 11:00 UTC, v-soukum approved these changes

2021-09-09 08:59 UTC, juhi037 requested changes

2021-09-09 08:59 UTC, juhi037 commented on src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Project.ps1
> +            $securityNamespacesObj = [WebRequestHelper]::InvokeGetWebRequest($namespacesApiURL);
$securityNamespacesObj has a standard value of "2e9eb7ed-3c0a-47d4-87c1-0ffdd275fd87", across ADO, so we can skip this extra API call
Refer: https://docs.microsoft.com/en-us/azure/devops/organizations/security/manage-tokens-namespaces?view=azure-devops#namespaces-and-their-ids

2021-09-09 08:59 UTC, juhi037 commented on src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Project.ps1
> +            $repoSecurityNamespaceId = ($securityNamespacesObj | Where-Object {$_.Name -eq "Git Repositories"}).namespaceId
same here we already have namespace this can be omitted

2021-09-09 08:59 UTC, juhi037 commented on src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Project.ps1
> +            if ([Helpers]::CheckMember($this.ControlSettings, "Repo.CheckForInheritedPermissions") -and $this.ControlSettings.Repo.CheckForInheritedPermissions) {
can we move these (2980 - 2984) to the constructor?

2021-09-09 08:59 UTC, juhi037 commented on src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Project.ps1
> +                $body = '{"contributionIds":["ms.vss-admin-web.security-view-permissions-data-provider"],"dataProviderContext":{"properties":{"subjectDescriptor":"","permissionSetId": "2e9eb7ed-3c0a-
here we are using the constant permission set Id, so please make it consistent by adding that constant in above places as well

2021-09-09 08:59 UTC, juhi037 commented on src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Project.ps1
> +                        $controlResult.AddMessage([VerificationResult]::Passed, "Build pipelines are not allowed to inherit excessive permissions for a broad group of users at project level.");
this message should be changed in context to repo: Broader groups are not granted excessive permissions on repositories

2021-09-09 08:59 UTC, juhi037 commented on src/AzSK.ADO/Framework/Core/SVT/ADO/ADO.Project.ps1
> +            $responseObj = $null;
should we also add list of excessive permissions : the following permissions are considered excessive

2021-09-09 11:12 UTC, closed without merging